# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: FunctionFullArchitecture
version: 1.0.0
summary: Full Hands on Lab Azure Function Architecture
description: Deploys a Full Function App Architecture with Azure Functions, CosmosDB, Azure Storage, Azure Key Vault, Azure App Insights and Azure API Management
runner: Bicep
templatePath: main.bicep

parameters:
  - id: name
    name: Environment name
    description: "Name of the environment"
    type: string
  - id: location
    name: location
    description: "Location to deploy the environment resources"
    type: string
    required: true
    allowed:
      - eastus
      - westus3
      - swedencentral
